# Generated by Django 4.2.13 on 2024-06-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PackChildFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.CharField(blank=True, max_length=5, null=True)),
                ('mes', models.CharField(blank=True, max_length=3, null=True)),
                ('cod_prov', models.CharField(blank=True, max_length=10, null=True)),
                ('cod_dist', models.CharField(blank=True, max_length=10, null=True)),
                ('provincia', models.CharField(blank=True, max_length=150, null=True)),
                ('distrito', models.CharField(blank=True, max_length=150, null=True)),
                ('establecimiento', models.CharField(blank=True, max_length=250, null=True)),
                ('documento', models.CharField(blank=True, max_length=15, null=True)),
                ('fec_nac', models.DateField(blank=True, null=True)),
                ('ctrl1rn', models.DateField(blank=True, null=True)),
                ('ctrl2rn', models.DateField(blank=True, null=True)),
                ('ctrl3rn', models.DateField(blank=True, null=True)),
                ('ctrl4rn', models.DateField(blank=True, null=True)),
                ('cumplern', models.CharField(blank=True, max_length=10, null=True)),
                ('cred1', models.DateField(blank=True, null=True)),
                ('cred2', models.DateField(blank=True, null=True)),
                ('neumo2', models.DateField(blank=True, null=True)),
                ('rota2', models.DateField(blank=True, null=True)),
                ('polio2', models.DateField(blank=True, null=True)),
                ('penta2', models.DateField(blank=True, null=True)),
                ('cred3', models.DateField(blank=True, null=True)),
                ('cred4', models.DateField(blank=True, null=True)),
                ('suple4', models.DateField(blank=True, null=True)),
                ('neumo4', models.DateField(blank=True, null=True)),
                ('rota4', models.DateField(blank=True, null=True)),
                ('penta4', models.DateField(blank=True, null=True)),
                ('polio4', models.DateField(blank=True, null=True)),
                ('cred5', models.DateField(blank=True, null=True)),
                ('suple5', models.DateField(blank=True, null=True)),
                ('cred6', models.DateField(blank=True, null=True)),
                ('tmz', models.DateField(blank=True, null=True)),
                ('dxAnemia', models.DateField(blank=True, null=True)),
                ('suple6', models.DateField(blank=True, null=True)),
                ('polio6', models.DateField(blank=True, null=True)),
                ('penta6', models.DateField(blank=True, null=True)),
                ('cred7', models.DateField(blank=True, null=True)),
                ('suple7', models.DateField(blank=True, null=True)),
                ('cred8', models.DateField(blank=True, null=True)),
                ('suple8', models.DateField(blank=True, null=True)),
                ('cred9', models.DateField(blank=True, null=True)),
                ('suple9', models.DateField(blank=True, null=True)),
                ('cred10', models.DateField(blank=True, null=True)),
                ('suple10', models.DateField(blank=True, null=True)),
                ('cred11', models.DateField(blank=True, null=True)),
                ('suple11', models.DateField(blank=True, null=True)),
                ('eval_oral', models.DateField(blank=True, null=True)),
                ('dif1', models.IntegerField(blank=True, null=True)),
                ('dif2', models.IntegerField(blank=True, null=True)),
                ('dif3', models.IntegerField(blank=True, null=True)),
                ('dif4', models.IntegerField(blank=True, null=True)),
                ('dif5', models.IntegerField(blank=True, null=True)),
                ('dif6', models.IntegerField(blank=True, null=True)),
                ('dif7', models.IntegerField(blank=True, null=True)),
                ('dif8', models.IntegerField(blank=True, null=True)),
                ('dif9', models.IntegerField(blank=True, null=True)),
                ('dif10', models.IntegerField(blank=True, null=True)),
                ('mide', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
