# Generated by Django 4.2.13 on 2024-07-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packchildfollow',
            old_name='cumplern',
            new_name='cod_eess',
        ),
        migrations.RemoveField(
            model_name='packchildfollow',
            name='mide',
        ),
        migrations.AddField(
            model_name='packchildfollow',
            name='ape_nombres',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='packchildfollow',
            name='autogenerado',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='packchildfollow',
            name='den',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packchildfollow',
            name='edad_mes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packchildfollow',
            name='num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packchildfollow',
            name='num_cred',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packchildfollow',
            name='num_rn',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packchildfollow',
            name='num_suple',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packchildfollow',
            name='num_vac',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packchildfollow',
            name='nutricion10',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packchildfollow',
            name='nutricion11',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packchildfollow',
            name='nutricion6',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packchildfollow',
            name='nutricion7',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packchildfollow',
            name='nutricion8',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packchildfollow',
            name='nutricion9',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packchildfollow',
            name='pn',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packchildfollow',
            name='programa',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
