# Generated by Django 4.2.13 on 2024-07-18 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_rename_cumplern_packchildfollow_cod_eess_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PregnantFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_prov', models.CharField(blank=True, max_length=10, null=True)),
                ('provincia', models.CharField(blank=True, max_length=150, null=True)),
                ('cod_dist', models.CharField(blank=True, max_length=10, null=True)),
                ('distrito', models.CharField(blank=True, max_length=150, null=True)),
                ('cod_eess', models.CharField(blank=True, max_length=10, null=True)),
                ('establecimiento', models.CharField(blank=True, max_length=250, null=True)),
                ('autogenerado', models.CharField(blank=True, max_length=60, null=True)),
                ('documento', models.CharField(blank=True, max_length=15, null=True)),
                ('ape_nombres', models.CharField(blank=True, max_length=200, null=True)),
                ('visit1', models.DateField(blank=True, null=True)),
                ('visit2', models.DateField(blank=True, null=True)),
                ('visit3', models.DateField(blank=True, null=True)),
                ('bacteruria', models.DateField(blank=True, null=True)),
                ('sifilis', models.DateField(blank=True, null=True)),
                ('tmz', models.DateField(blank=True, null=True)),
                ('vih', models.DateField(blank=True, null=True)),
                ('perf_obst', models.DateField(blank=True, null=True)),
                ('ctrl1', models.DateField(blank=True, null=True)),
                ('ctrl2', models.DateField(blank=True, null=True)),
                ('ctrl3', models.DateField(blank=True, null=True)),
                ('ctrl4', models.DateField(blank=True, null=True)),
                ('ctrl5', models.DateField(blank=True, null=True)),
                ('ctrl6', models.DateField(blank=True, null=True)),
                ('ctrl7', models.DateField(blank=True, null=True)),
                ('ctrl8', models.DateField(blank=True, null=True)),
                ('ctrl9', models.DateField(blank=True, null=True)),
                ('ctrl10', models.DateField(blank=True, null=True)),
                ('ctrl11', models.DateField(blank=True, null=True)),
                ('suple1', models.DateField(blank=True, null=True)),
                ('suple2', models.DateField(blank=True, null=True)),
                ('suple3', models.DateField(blank=True, null=True)),
                ('suple4', models.DateField(blank=True, null=True)),
                ('suple5', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
