# Generated by Django 4.2.13 on 2024-07-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_pregnantfollow'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregnantfollow',
            name='den',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pregnantfollow',
            name='num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
