# Generated by Django 4.2.13 on 2024-08-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_pregnantfollow_c10_c11_pregnantfollow_c1_c2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregnantfollow',
            name='fpp',
            field=models.DateField(blank=True, max_length=6, null=True),
        ),
    ]
