# Generated by Django 4.2.13 on 2024-09-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0006_alter_pregnantfollow_fpp'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregnantfollow',
            name='aro',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pregnantfollow',
            name='bro',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pregnantfollow',
            name='carbonato1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pregnantfollow',
            name='carbonato2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pregnantfollow',
            name='carbonato3',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pregnantfollow',
            name='carbonato4',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pregnantfollow',
            name='carbonato5',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pregnantfollow',
            name='cmp1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pregnantfollow',
            name='cmp2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pregnantfollow',
            name='cmp3',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pregnantfollow',
            name='dt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pregnantfollow',
            name='dtpa',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pregnantfollow',
            name='dx_anemia2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pregnantfollow',
            name='epn1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pregnantfollow',
            name='epn2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pregnantfollow',
            name='epn3',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pregnantfollow',
            name='epn4',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pregnantfollow',
            name='epn5',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pregnantfollow',
            name='epn6',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pregnantfollow',
            name='hepatitis',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pregnantfollow',
            name='influenza',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pregnantfollow',
            name='nutricion1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pregnantfollow',
            name='nutricion2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pregnantfollow',
            name='nutricion3',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pregnantfollow',
            name='nutricion4',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pregnantfollow',
            name='nutricion5',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pregnantfollow',
            name='nutricion6',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pregnantfollow',
            name='odontologia1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pregnantfollow',
            name='odontologia2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pregnantfollow',
            name='ppo1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pregnantfollow',
            name='ppo2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pregnantfollow',
            name='ppo3',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pregnantfollow',
            name='ppo4',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pregnantfollow',
            name='ppo5',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pregnantfollow',
            name='ppo6',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pregnantfollow',
            name='psicologia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pregnantfollow',
            name='suple_ant13_2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pregnantfollow',
            name='suple_ant13_3',
            field=models.DateField(blank=True, null=True),
        ),
    ]
