# Generated by Django 4.2.13 on 2024-09-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0008_pregnantfollow_ate_parto'),
    ]

    operations = [
        migrations.AddField(
            model_name='packchildfollow',
            name='cod_dep',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='packchildfollow',
            name='departamento',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='pregnantfollow',
            name='cod_dep',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pregnantfollow',
            name='departamento',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
