# Generated by Django 4.2.13 on 2024-07-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_rename_apo1_ref_coverage_dpta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metacoverage',
            name='cod_eess',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='metacoverage',
            name='establecimiento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
