# Generated by Django 4.2.13 on 2024-09-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_metacoverage_cod_eess_metacoverage_establecimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverage',
            name='cod_dep',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='coverage',
            name='departamento',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
