# Generated by Django 4.2.13 on 2024-09-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_coverage_cod_dep_coverage_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='metacoverage',
            name='cod_dep',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='metacoverage',
            name='departamento',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
