from django.db import models

# Create your models here.
class PackChildFollow(models.Model):
    anio = models.CharField(max_length=5, blank=True, null=True)
    mes = models.CharField(max_length=3, blank=True, null=True)
    cod_dep = models.CharField(max_length=10, blank=True, null=True)
    departamento = models.CharField(max_length=70, blank=True, null=True)
    cod_prov = models.CharField(max_length=10, blank=True, null=True)
    cod_dist = models.CharField(max_length=10, blank=True, null=True)
    provincia = models.CharField(max_length=150, blank=True, null=True)
    distrito = models.CharField(max_length=150, blank=True, null=True)
    cod_eess = models.CharField(max_length=10, blank=True, null=True)
    establecimiento = models.CharField(max_length=250, blank=True, null=True)
    documento = models.CharField(max_length=15, blank=True, null=True)
    ape_nombres= models.CharField(max_length=150, blank=True, null=True)
    fec_nac = models.DateField(blank=True, null=True)
    autogenerado = models.CharField(max_length=40, blank=True, null=True)
    edad_mes = models.IntegerField(blank=True, null=True)
    ctrl1rn = models.DateField(blank=True, null=True)
    ctrl2rn = models.DateField(blank=True, null=True)
    ctrl3rn = models.DateField(blank=True, null=True)
    ctrl4rn = models.DateField(blank=True, null=True)
    cred1 = models.DateField(blank=True, null=True)
    cred2 = models.DateField(blank=True, null=True)
    neumo2 = models.DateField(blank=True, null=True)
    rota2 = models.DateField(blank=True, null=True)
    polio2 = models.DateField(blank=True, null=True)
    penta2 = models.DateField(blank=True, null=True)
    cred3 = models.DateField(blank=True, null=True)
    cred4 = models.DateField(blank=True, null=True)
    suple4 = models.DateField(blank=True, null=True)
    neumo4 = models.DateField(blank=True, null=True)
    rota4 = models.DateField(blank=True, null=True)
    penta4 = models.DateField(blank=True, null=True)
    polio4 = models.DateField(blank=True, null=True)
    cred5 = models.DateField(blank=True, null=True)
    suple5 = models.DateField(blank=True, null=True)
    cred6 = models.DateField(blank=True, null=True)
    tmz = models.DateField(blank=True, null=True)
    dxAnemia = models.DateField(blank=True, null=True)
    suple6 = models.DateField(blank=True, null=True)
    polio6 = models.DateField(blank=True, null=True)
    penta6 = models.DateField(blank=True, null=True)
    cred7 = models.DateField(blank=True, null=True)
    suple7 = models.DateField(blank=True, null=True)
    cred8 = models.DateField(blank=True, null=True)
    suple8 = models.DateField(blank=True, null=True)
    cred9 = models.DateField(blank=True, null=True)
    suple9 = models.DateField(blank=True, null=True)
    cred10 = models.DateField(blank=True, null=True)
    suple10 = models.DateField(blank=True, null=True)
    cred11 = models.DateField(blank=True, null=True)
    suple11 = models.DateField(blank=True, null=True)
    eval_oral = models.DateField(blank=True, null=True)
    nutricion6 = models.DateField(blank=True, null=True)
    nutricion7 = models.DateField(blank=True, null=True)
    nutricion8 = models.DateField(blank=True, null=True)
    nutricion9 = models.DateField(blank=True, null=True)
    nutricion10 = models.DateField(blank=True, null=True)
    nutricion11 = models.DateField(blank=True, null=True)
    programa = models.CharField(max_length=150, blank=True, null=True)
    pn = models.IntegerField(blank=True, null=True)
    dif1 = models.IntegerField(blank=True, null=True)
    dif2 = models.IntegerField(blank=True, null=True)
    dif3 = models.IntegerField(blank=True, null=True)
    dif4 = models.IntegerField(blank=True, null=True)
    dif5 = models.IntegerField(blank=True, null=True)
    dif6 = models.IntegerField(blank=True, null=True)
    dif7 = models.IntegerField(blank=True, null=True)
    dif8 = models.IntegerField(blank=True, null=True)
    dif9 = models.IntegerField(blank=True, null=True)
    dif10 = models.IntegerField(blank=True, null=True)
    den = models.IntegerField(blank=True, null=True)
    num = models.IntegerField(blank=True, null=True)
    num_rn = models.IntegerField(blank=True, null=True)
    num_cred = models.IntegerField(blank=True, null=True)
    num_vac = models.IntegerField(blank=True, null=True)
    num_suple = models.IntegerField(blank=True, null=True)

    def natural_key(self):
        return self.pk, self.anio, self.mes, self.cod_prov, self.cod_dist, self.cod_eess,\
               self.provincia, self.distrito, self.establecimiento, self.documento, self.ape_nombres,\
               self.fec_nac, self.autogenerado, self.edad_mes, self.ctrl1rn, self.ctrl2rn, self.ctrl3rn, self.ctrl4rn,\
               self.cred1, self.cred2, self.neumo2, self.rota2, self.polio2, self.penta2, self.cred3, self.cred4,\
               self.suple4, self.neumo4, self.rota4, self.penta4, self.polio4, self.cred5, self.suple5, self.cred6, \
               self.tmz, self.dxAnemia, self.suple6, self.polio6, self.penta6, self.cred7, self.suple7, self.cred8, \
               self.suple8, self.cred9, self.suple9, self.cred10, self.suple10, self.cred11, self.suple11, self.eval_oral, \
                self.nutricion6, self.nutricion7, self.nutricion8, self.nutricion9, self.nutricion10, self.nutricion11, self.programa, self.pn, \
               self.dif1, self.dif2, self.dif3, self.dif4, self.dif5, self.dif6, self.dif7, self.dif8, self.dif9, self.dif10, self.num, self.num_rn, self.num_cred, self.num_vac, self.num_suple, self.den, self.num

    def __str__(self):
        return '%s %s, %s' % (self.provincia, self.distrito, self.establecimiento)


class PregnantFollow(models.Model):
    cod_dep = models.CharField(max_length=10, blank=True, null=True)
    departamento = models.CharField(max_length=70, blank=True, null=True)
    cod_prov = models.CharField(max_length=10, blank=True, null=True)
    provincia = models.CharField(max_length=150, blank=True, null=True)
    cod_dist = models.CharField(max_length=10, blank=True, null=True)
    distrito = models.CharField(max_length=150, blank=True, null=True)
    cod_eess = models.CharField(max_length=10, blank=True, null=True)
    establecimiento = models.CharField(max_length=250, blank=True, null=True)
    autogenerado = models.CharField(max_length=60, blank=True, null=True)
    documento = models.CharField(max_length=15, blank=True, null=True)
    ape_nombres= models.CharField(max_length=200, blank=True, null=True)
    visit1 = models.DateField(blank=True, null=True)
    visit2 = models.DateField(blank=True, null=True)
    visit3 = models.DateField(blank=True, null=True)
    bacteruria = models.DateField(blank=True, null=True)
    sifilis = models.DateField(blank=True, null=True)
    tmz = models.DateField(blank=True, null=True)
    vih = models.DateField(blank=True, null=True)
    perf_obst = models.DateField(blank=True, null=True)
    ctrl1 = models.DateField(blank=True, null=True)
    ctrl2 = models.DateField(blank=True, null=True)
    ctrl3 = models.DateField(blank=True, null=True)
    ctrl4 = models.DateField(blank=True, null=True)
    ctrl5 = models.DateField(blank=True, null=True)
    ctrl6 = models.DateField(blank=True, null=True)
    ctrl7 = models.DateField(blank=True, null=True)
    ctrl8 = models.DateField(blank=True, null=True)
    ctrl9 = models.DateField(blank=True, null=True)
    ctrl10 = models.DateField(blank=True, null=True)
    ctrl11 = models.DateField(blank=True, null=True)
    suple1 = models.DateField(blank=True, null=True)
    suple2 = models.DateField(blank=True, null=True)
    suple3 = models.DateField(blank=True, null=True)
    suple4 = models.DateField(blank=True, null=True)
    suple5 = models.DateField(blank=True, null=True)
    den = models.IntegerField(blank=True, null=True)
    num = models.IntegerField(blank=True, null=True)
    edad_cap = models.IntegerField(blank=True, null=True)
    max_sem13 = models.DateField(blank=True, null=True)
    sem_captada = models.CharField(max_length=60, blank=True, null=True)
    fur = models.DateField(blank=True, null=True)
    peso = models.CharField(max_length=6, blank=True, null=True)
    talla = models.CharField(max_length=6, blank=True, null=True)
    fpp = models.DateField(max_length=6, blank=True, null=True)
    laboratorio = models.IntegerField(blank=True, null=True)
    result = models.CharField(max_length=200, blank=True, null=True)
    dx_anemia = models.DateField(blank=True, null=True)
    dx_anemia2 = models.DateField(blank=True, null=True)
    suple_ant13 = models.DateField(blank=True, null=True)
    ini_sem28 = models.DateField(blank=True, null=True)
    ini_sem33 = models.DateField(blank=True, null=True)
    c1_c2 = models.IntegerField(blank=True, null=True)
    c2_c3 = models.IntegerField(blank=True, null=True)
    c3_c4 = models.IntegerField(blank=True, null=True)
    c4_c5 = models.IntegerField(blank=True, null=True)
    c5_c6 = models.IntegerField(blank=True, null=True)
    c6_c7 = models.IntegerField(blank=True, null=True)
    c7_c8 = models.IntegerField(blank=True, null=True)
    c8_c9 = models.IntegerField(blank=True, null=True)
    c9_c10 = models.IntegerField(blank=True, null=True)
    c10_c11 = models.IntegerField(blank=True, null=True)
    aro = models.DateField(blank=True, null=True)
    bro = models.DateField(blank=True, null=True)
    cmp1 = models.DateField(blank=True, null=True)
    cmp2 = models.DateField(blank=True, null=True)
    cmp3 = models.DateField(blank=True, null=True)
    carbonato1 = models.DateField(blank=True, null=True)
    carbonato2 = models.DateField(blank=True, null=True)
    carbonato3 = models.DateField(blank=True, null=True)
    carbonato4 = models.DateField(blank=True, null=True)
    carbonato5 = models.DateField(blank=True, null=True)
    nutricion1 = models.DateField(blank=True, null=True)
    nutricion2 = models.DateField(blank=True, null=True)
    nutricion3 = models.DateField(blank=True, null=True)
    nutricion4 = models.DateField(blank=True, null=True)
    nutricion5 = models.DateField(blank=True, null=True)
    nutricion6 = models.DateField(blank=True, null=True)
    odontologia1 = models.DateField(blank=True, null=True)
    odontologia2 = models.DateField(blank=True, null=True)
    psicologia = models.DateField(blank=True, null=True)
    dt = models.DateField(blank=True, null=True)
    dtpa = models.DateField(blank=True, null=True)
    hepatitis = models.DateField(blank=True, null=True)
    influenza = models.DateField(blank=True, null=True)
    ppo1 = models.DateField(blank=True, null=True)
    ppo2 = models.DateField(blank=True, null=True)
    ppo3 = models.DateField(blank=True, null=True)
    ppo4 = models.DateField(blank=True, null=True)
    ppo5 = models.DateField(blank=True, null=True)
    ppo6 = models.DateField(blank=True, null=True)
    epn1 = models.DateField(blank=True, null=True)
    epn2 = models.DateField(blank=True, null=True)
    epn3 = models.DateField(blank=True, null=True)
    epn4 = models.DateField(blank=True, null=True)
    epn5 = models.DateField(blank=True, null=True)
    epn6 = models.DateField(blank=True, null=True)
    suple_ant13_2 = models.DateField(blank=True, null=True)
    suple_ant13_3 = models.DateField(blank=True, null=True)
    ate_parto = models.DateField(blank=True, null=True)

    def natural_key(self):
        return self.pk, self.cod_prov, self.provincia, self.cod_dist, self.distrito, self.cod_eess, self.establecimiento,\
               self.documento, self.ape_nombres, self.autogenerado, self.documento, self.ape_nombres, self.bacteruria,\
               self.sifilis, self.tmz, self.vih, self.perf_obst, self.ctrl1, self.ctrl2, self.ctrl3, self.ctrl4, self.ctrl5,\
               self.ctrl6, self.ctrl7, self.ctrl8, self.ctrl9, self.ctrl10, self.ctrl11, self.suple1, self.suple2, self.suple3,\
               self.suple4, self.suple5, self.visit1, self.visit2, self.visit3, self.den,self.num

    def __str__(self):
        return '%s %s, %s' % (self.provincia, self.distrito, self.establecimiento)

