# Generated by Django 4.2.13 on 2024-08-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code_ca',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='type_ca',
            field=models.CharField(choices=[('DP', 'DEPARTAMENTO'), ('PR', 'PROVINCIA'), ('DS', 'DISTRITO'), ('CA', 'CENTRO ASISTENCIAL')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
