# Generated by Django 4.2.13 on 2024-06-13 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='id',
        ),
        migrations.RemoveField(
            model_name='distrito',
            name='id',
        ),
        migrations.RemoveField(
            model_name='establecimiento',
            name='id',
        ),
        migrations.RemoveField(
            model_name='provincia',
            name='id',
        ),
        # migrations.AlterField(
        #     model_name='departamento',
        #     name='codigo',
        #     field=models.CharField(max_length=3, primary_key=True, serialize=False),
        # ),
        # migrations.AlterField(
        #     model_name='distrito',
        #     name='codigo',
        #     field=models.CharField(max_length=7, primary_key=True, serialize=False),
        # ),
        # migrations.AlterField(
        #     model_name='distrito',
        #     name='parent',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.provincia'),
        # ),
        # migrations.AlterField(
        #     model_name='establecimiento',
        #     name='codigo',
        #     field=models.CharField(max_length=5, primary_key=True, serialize=False),
        # ),
        # migrations.AlterField(
        #     model_name='establecimiento',
        #     name='parent',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.distrito'),
        # ),
        # migrations.AlterField(
        #     model_name='provincia',
        #     name='codigo',
        #     field=models.CharField(max_length=3, primary_key=True, serialize=False),
        # ),
        # migrations.AlterField(
        #     model_name='provincia',
        #     name='parent',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.departamento'),
        # ),
    ]
