# Generated by Django 4.2.13 on 2024-06-13 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_departamento_id_remove_distrito_id_and_more'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='distrito',
        #     name='parent',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.provincia'),
        # ),
        # migrations.AlterField(
        #     model_name='establecimiento',
        #     name='parent',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.distrito'),
        # ),
        # migrations.AlterField(
        #     model_name='provincia',
        #     name='parent',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.departamento'),
        # ),
    ]
