# Generated by Django 4.2.13 on 2024-06-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_distrito_parent_alter_establecimiento_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distrito',
            name='parent',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='parent',
            field=models.CharField(default=1, max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='provincia',
            name='parent',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
