# Generated by Django 4.2.13 on 2024-06-13 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_distrito_parent_alter_establecimiento_parent_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Distrito',
        ),
        migrations.DeleteModel(
            name='Establecimiento',
        ),
        migrations.DeleteModel(
            name='Provincia',
        ),
    ]
