# Generated by Django 4.2.13 on 2024-06-13 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_departamento_codigo_provincia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('codigo', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.provincia')),
            ],
        ),
    ]
