# Generated by Django 4.2.13 on 2024-07-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anemia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.CharField(blank=True, max_length=5, null=True)),
                ('mes', models.CharField(blank=True, max_length=3, null=True)),
                ('cod_dep', models.CharField(blank=True, max_length=5, null=True)),
                ('cod_prov', models.CharField(blank=True, max_length=5, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('cod_dist', models.CharField(blank=True, max_length=8, null=True)),
                ('distrito', models.CharField(blank=True, max_length=150, null=True)),
                ('cod_eess', models.CharField(blank=True, max_length=5, null=True)),
                ('establecimiento', models.CharField(blank=True, max_length=250, null=True)),
                ('documento', models.CharField(blank=True, max_length=15, null=True)),
                ('ape_nombres', models.CharField(blank=True, max_length=200, null=True)),
                ('fec_nac', models.DateField(blank=True, null=True)),
                ('edad_mes', models.DateField(blank=True, null=True)),
                ('dosaje1', models.DateField(blank=True, null=True)),
                ('result1', models.DateField(blank=True, null=True)),
                ('dosaje2', models.DateField(blank=True, null=True)),
                ('result2', models.DateField(blank=True, null=True)),
                ('dx_anemia1', models.DateField(blank=True, null=True)),
                ('dx_anemia2', models.DateField(blank=True, null=True)),
                ('nutricion6', models.DateField(blank=True, null=True)),
                ('nutricion7', models.DateField(blank=True, null=True)),
                ('nutricion8', models.DateField(blank=True, null=True)),
                ('nutricion9', models.DateField(blank=True, null=True)),
                ('nutricion10', models.DateField(blank=True, null=True)),
                ('nutricion11', models.DateField(blank=True, null=True)),
                ('den', models.IntegerField(blank=True, null=True)),
                ('num', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
