# Generated by Django 4.2.13 on 2024-07-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_up', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anemia',
            name='result1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='anemia',
            name='result2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
