# Generated by Django 4.2.13 on 2024-07-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_up', '0002_alter_anemia_result1_alter_anemia_result2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anemia',
            name='anio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anemia',
            name='mes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
