# Generated by Django 4.2.13 on 2024-07-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_up', '0003_alter_anemia_anio_alter_anemia_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anemia',
            name='edad_mes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
