# Generated by Django 4.2.13 on 2024-09-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_up', '0006_vaccinexpat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinexpat',
            name='descripcion',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='vaccinexpat',
            name='documento',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
