# Generated by Django 4.2.13 on 2024-10-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_up', '0008_vaccinexpat_eess'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inmunization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_eess', models.IntegerField(blank=True, null=True)),
                ('eess', models.CharField(blank=True, max_length=200, null=True)),
                ('autogenerado', models.CharField(blank=True, max_length=50, null=True)),
                ('documento', models.CharField(blank=True, max_length=25, null=True)),
                ('paciente', models.CharField(blank=True, max_length=300, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('fec_nac', models.DateField(blank=True, null=True)),
                ('hvb', models.DateField(blank=True, null=True)),
                ('bcg', models.DateField(blank=True, null=True)),
                ('rota2m', models.DateField(blank=True, null=True)),
                ('apo2m', models.DateField(blank=True, null=True)),
                ('penta2m', models.DateField(blank=True, null=True)),
                ('neumo2m', models.DateField(blank=True, null=True)),
                ('rota4m', models.DateField(blank=True, null=True)),
                ('apo4m', models.DateField(blank=True, null=True)),
                ('penta4m', models.DateField(blank=True, null=True)),
                ('neumo4m', models.DateField(blank=True, null=True)),
                ('apo6m', models.DateField(blank=True, null=True)),
                ('penta6m', models.DateField(blank=True, null=True)),
                ('neumo6m', models.DateField(blank=True, null=True)),
                ('infl6m', models.DateField(blank=True, null=True)),
                ('infl7m', models.DateField(blank=True, null=True)),
                ('spr1', models.DateField(blank=True, null=True)),
                ('varicela', models.DateField(blank=True, null=True)),
                ('hiv', models.DateField(blank=True, null=True)),
                ('ama', models.DateField(blank=True, null=True)),
                ('spr2', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
