# Generated by Django 4.2.13 on 2024-10-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_up', '0010_rename_id_eess_inmunization_cod_eess'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmunization',
            name='cod_dep',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmunization',
            name='cod_dist',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmunization',
            name='cod_prov',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='inmunization',
            name='departamento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inmunization',
            name='distrito',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inmunization',
            name='provincia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
