# Generated by Django 4.2.13 on 2024-11-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_up', '0011_inmunization_cod_dep_inmunization_cod_dist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmunization',
            name='apo1_ref',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmunization',
            name='dpt1_ref',
            field=models.DateField(blank=True, null=True),
        ),
    ]
