# Generated by Django 4.2.13 on 2024-11-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_up', '0012_inmunization_apo1_ref_inmunization_dpt1_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmunization',
            name='documento',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
