# Generated by Django 4.2.13 on 2024-12-04 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_up', '0013_alter_inmunization_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inmunization_C',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_dep', models.IntegerField(blank=True, null=True)),
                ('departamento', models.CharField(blank=True, max_length=50, null=True)),
                ('cod_prov', models.CharField(blank=True, max_length=5, null=True)),
                ('provincia', models.CharField(blank=True, max_length=50, null=True)),
                ('cod_dist', models.IntegerField(blank=True, null=True)),
                ('distrito', models.CharField(blank=True, max_length=100, null=True)),
                ('cod_eess', models.IntegerField(blank=True, null=True)),
                ('eess', models.CharField(blank=True, max_length=200, null=True)),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('mes', models.IntegerField(blank=True, null=True)),
                ('bcg', models.IntegerField(blank=True, null=True)),
                ('hvb', models.IntegerField(blank=True, null=True)),
                ('rota2m', models.IntegerField(blank=True, null=True)),
                ('apo2m', models.IntegerField(blank=True, null=True)),
                ('penta2m', models.IntegerField(blank=True, null=True)),
                ('neumo2m', models.IntegerField(blank=True, null=True)),
                ('apo4m', models.IntegerField(blank=True, null=True)),
                ('penta4m', models.IntegerField(blank=True, null=True)),
                ('rota4m', models.IntegerField(blank=True, null=True)),
                ('neumo4m', models.IntegerField(blank=True, null=True)),
                ('apo6m', models.IntegerField(blank=True, null=True)),
                ('penta6m', models.IntegerField(blank=True, null=True)),
                ('infl1', models.IntegerField(blank=True, null=True)),
                ('infl2', models.IntegerField(blank=True, null=True)),
                ('neumo6m', models.IntegerField(blank=True, null=True)),
                ('infl6m', models.IntegerField(blank=True, null=True)),
                ('infl7m', models.IntegerField(blank=True, null=True)),
                ('spr1', models.IntegerField(blank=True, null=True)),
                ('neumo3', models.IntegerField(blank=True, null=True)),
                ('varicela', models.IntegerField(blank=True, null=True)),
                ('infl1a', models.IntegerField(blank=True, null=True)),
                ('inflb', models.IntegerField(blank=True, null=True)),
                ('hib', models.IntegerField(blank=True, null=True)),
                ('ama', models.IntegerField(blank=True, null=True)),
                ('spr2', models.IntegerField(blank=True, null=True)),
                ('ref_dpt', models.IntegerField(blank=True, null=True)),
                ('ref_apo', models.IntegerField(blank=True, null=True)),
                ('ref_ipv', models.IntegerField(blank=True, null=True)),
                ('varicela2', models.IntegerField(blank=True, null=True)),
                ('hepatitis', models.IntegerField(blank=True, null=True)),
                ('infl2a', models.IntegerField(blank=True, null=True)),
                ('infl3a', models.IntegerField(blank=True, null=True)),
                ('infl4a', models.IntegerField(blank=True, null=True)),
                ('ref_apo2', models.IntegerField(blank=True, null=True)),
                ('vph1', models.IntegerField(blank=True, null=True)),
                ('vph2', models.IntegerField(blank=True, null=True)),
                ('vph_du', models.IntegerField(blank=True, null=True)),
                ('gest_dt1', models.IntegerField(blank=True, null=True)),
                ('gest_dt2', models.IntegerField(blank=True, null=True)),
                ('gest_tdap', models.IntegerField(blank=True, null=True)),
                ('gest_infl', models.IntegerField(blank=True, null=True)),
                ('neumo_adult', models.IntegerField(blank=True, null=True)),
                ('infl_adult', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
