# Generated by Django 4.2.13 on 2024-12-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_up', '0014_inmunization_c'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inmunization',
            old_name='apo1_ref',
            new_name='gest_dt1',
        ),
        migrations.RenameField(
            model_name='inmunization',
            old_name='dpt1_ref',
            new_name='gest_dt2',
        ),
        migrations.RenameField(
            model_name='inmunization',
            old_name='hiv',
            new_name='gest_infl',
        ),
        migrations.RemoveField(
            model_name='inmunization',
            name='autogenerado',
        ),
        migrations.RemoveField(
            model_name='inmunization_c',
            name='infl1',
        ),
        migrations.RemoveField(
            model_name='inmunization_c',
            name='infl2',
        ),
        migrations.RemoveField(
            model_name='inmunization_c',
            name='neumo3',
        ),
        migrations.AddField(
            model_name='inmunization',
            name='edadm',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='inmunization',
            name='gest_tdap',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmunization',
            name='hepatitis',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmunization',
            name='hib',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmunization',
            name='infl1a',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmunization',
            name='infl2a',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmunization',
            name='infl3a',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmunization',
            name='infl4a',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmunization',
            name='infl_adult',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmunization',
            name='inflb',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmunization',
            name='neumo_adult',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmunization',
            name='ref_apo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmunization',
            name='ref_apo2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmunization',
            name='ref_dpt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmunization',
            name='ref_ipv',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmunization',
            name='varicela2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmunization',
            name='vph1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmunization',
            name='vph2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmunization',
            name='vph_du',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inmunization',
            name='edad',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
